---
title: "Experimental Vibratory Analysis"
description: |
  Data analysis for the Article 2
author:
  - first_name: "Fangkai"
    last_name: "Xue"
    url: 
    affiliation: ERPI
    affiliation_url: 
  - first_name: "Fabio"
    last_name: "CRUZ"
    url: 
    affiliation: ERPI
    affiliation_url: 
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
#repository_url: https://github.com/LF2L/everest-bio
#bibliography: 03-comportement.bib
#nocite: '@*'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Options for Knirt
knitr::opts_chunk$set(echo = FALSE,  include=FALSE, warning = FALSE, message = FALSE)
options(knitr.kable.NA = '-')

# Packages for the analysis
library(tidyverse)
library(here)
library(readxl)
library(kableExtra)
library(ggpubr)

## Ggplot Theme setting
theme_set(theme_bw(base_size = 15, base_family = "Palatino")) 
```

## Data from December 2020


```{r Data, eval=FALSE}

# Reading data ----
## Loading the data from Excel
files <- dir("Data Decembre 2020/", recursive=TRUE, full.names=TRUE, pattern="*.xlsx")

## Infor for PLA
#PLA  <- lapply(excel_sheets(path = files[2])[8:9], read_excel, path = files[2] ) %>% set_names("Amplitude", "Frequency") 

#PLA %>% map("Amplitude", rownames_to_column(var = "ID") )

  
Test <- read_excel(files[2], sheet = "Amplitude") %>% 
  rownames_to_column(var = "ID") %>% gather(ID, value = "Amplitude") %>% 
  rownames_to_column(var = "Measure")

Test2 <- 
  read_excel(files[2], sheet = "Frequency") %>% 
  rownames_to_column(var = "ID") %>% 
  gather(ID, value = "Frequency") %>% rownames_to_column(var = "Measure")


## Raw data of PLA
PLA <- left_join(Test, Test2, by=c("Measure", "ID" ))

## Creating a nested dataframe
PLA <- PLA %>% group_by(ID) %>% nest()


rm(Test, Test2)
```




```{r Resonance, eval=FALSE}

Resonance_fun <- function(Test) {

  # Split the data in two ranges
  Range_1 <- Test[1:2500,]
  Range_2 <- Test[2500 : 4096 ,]
  
  A <- Range_1$Frequency[ggpmisc:::find_peaks(Range_1$Amplitude, span = 5,
  ignore_threshold = 0.5)]
  
  B <- Range_2$Frequency[ggpmisc:::find_peaks(Range_2$Amplitude, span = 5,
  ignore_threshold = 0.11)]

  Modes <- tibble(
    Mode.1 = A[1],
    Mode.2 = A[2],
    Mode.3 = B[1],
    Mode.4 = B[2],
    Mode.5 = B[3]
  )
  
  return(Modes)
}

## Adding the Resonance values
PLA <- PLA %>% mutate(Freq = map_df( data, Resonance_fun))   


require(ggpmisc)
## Testtin the peak function
Test <- PLA[[2]][[36]]

Test$Frequency[ggpmisc:::find_peaks(Test$Amplitude, span = 10, ignore_threshold = 0.5)]

ggplot(Test[1:2500,] , aes(x = Frequency, y= Amplitude)) +
    geom_point( alpha = 1/10) + stat_peaks(col = "red", span = 5,
  ignore_threshold = 0.5) 

ggplot(Test[2500 : 4096 ,] , aes(x = Frequency, y= Amplitude)) +
    geom_point( alpha = 1/10) + stat_peaks(col = "red", span = 5,
  ignore_threshold = 0.11) 


```


## ANOVA
Last update: `r Sys.Date()`

```{r, include=TRUE}

# Reading the Data
Anova <- read_excel(here("Data Decembre 2020/ANOVA.xlsx")) 
Anova <- Anova %>% set_names(c("Raster", "Temperature", "Layer", "Speed", "Frequency.I", "Frequency.II" ))

# Changing the variables as factors
Anova <- Anova %>% mutate(Raster = factor(Raster),
                          Temperature = factor(Temperature),
                          Layer = factor(Layer),
                          Speed = factor(Speed)
                          )

# Longer table
Anova <- Anova %>% pivot_longer(cols = Frequency.I:Frequency.II)
Anova <- Anova %>% select(-name)

# Ploting the data
Anova %>%  
  kbl(booktabs = T, digits = c(0, 1, 3, 3, 3, 5),
      caption = "Data for Anova",  
      linesep = "")  %>%
  kable_styling(latex_options = c("striped"))

```





### Anova without Interactions
```{r Anova.noInter, include=TRUE}
## Creating the Linear Model without interactions
### Witouth interactions
Model.anv <- lm(value ~ Raster+Temperature+Layer+Speed, data = Anova)
anova(Model.anv)
```



### Anova with Interactions

```{r Anova.Inter, include=TRUE}
### With interactions
Model.anv <- lm(value ~ (.)^2  , data = Anova)

#summary(Total_model)
anova(Model.anv)
```


## Graphic of the means

```{r, include=TRUE}
test <- Anova %>% pivot_longer(!value, names_to = "Variables", values_to = "Level") %>% 
  select(Variables, Level, value)

ggboxplot(test, x = "Variables", y = "value", color = "Level",  
          add = "jitter", legend = "top") +
  geom_hline(yintercept = mean(test$value), linetype = 2) +
  coord_cartesian(ylim = c(18, 28))

```

### Interaction Raster Vs. Layer
```{r, include=TRUE}
ggline(Anova, x = "Layer", y = "value", color = "Raster",
       add = c("mean_se"), palette = "jco")
```

### Interaction Temperature Vs. Layer
```{r, include=TRUE}
ggline(Anova, x = "Temperature", y = "value", color = "Layer",
       add = c("mean_se"), palette = "jco")
```


